version: '3.8'  # Specify the Docker Compose version

services:
  mysqldb:  # Define a separate service for the database (modify if not using MySQL)
    image: mysql:5.7
    restart: unless-sytopped # Use a pre-built MySQL image
    environment:
      - MYSQL_ROOT_PASSWORD:   # Set the root password (change for production)
      - MYSQL_DATABASE: achat
    Ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
     # Persist data volume for the database
  achat:
    build: .  # Build the image from the current directory (context)
    depends_on:
      - mysqldb
    image: raouendjebbi/achat:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:8089/achat?createDatabaseIfNotExist=true",
      "spring.datasource.username": "root",
      "spring.datasource.password": null,
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"

      }'
    stdin_open: true
    tty: true

  volumes:
    db: # Map container port 8080 to host port 8080

