version: '3.8'  # Specify the Docker Compose version

services:
  db:  # Define a separate service for the database (modify if not using MySQL)
    image: mysql:8.0  # Use a pre-built MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password (change for production)
      MYSQL_DATABASE: achatdb  # Set the database name
  achat:
    build: .  # Build the image from the current directory (context)
    depends_on:
      - db
    ports:
      - "8089:8089"  # Map container port 8080 to host port 8080
    environment:
      # Add environment variables for database connection (if needed)
      - spring.datasource.url: jdbc:mysql://db:3306/achatdb  # Example
