version: '3.8'  # Specify the Docker Compose version

services:
  db:  # Define a separate service for the database (modify if not using MySQL)
    image: mysql:8.0  # Use a pre-built MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password (change for production)
      MYSQL_DATABASE: achatdb  # Set the database name
    volumes:
      - db-data:/var/lib/mysql  # Persist data volume for the database
  achat:
    build: .  # Build the image from the current directory (context)
    depends_on:
      - db
    ports:
      - "8089:8089"  # Map container port 8080 to host port 8080
volumes:
  db-data:  # Define a named volume for database persistence
